### ISSUE TITLE
not parsing config.ini

### ISSUE THREAD

**Issue by Kali123411** [Konyanj0278/BestBuy-Automated-Checkout#4]
DevTools listening on ws://127.0.0.1:54318/devtools/browser/2047535e-296e-4850-b958-b6a52d65ccdc
Traceback (most recent call last):
  File "C:\Users\XX\Desktop\BestBuy-Automated-Checkout-main\BestBuybot.py", line 134, in <module>
    bot = BBYbot(config_file)
  File "C:\Users\XX\Desktop\BestBuy-Automated-Checkout-main\BestBuybot.py", line 16, in __init__
    self.username=config.get('BBY_ACCOUNT','USERNAME')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'BBY_ACCOUNT'

**Comment by Kali123411** [comment]
Works now perfectly, thank you. Had to run it in Python IDLE now working fine.
